// Full 100-Question NFL Trivia Deck (Final, Verified)

const deck = [
  { q:"Who caught the Minneapolis Miracle?", hint:"Vikings WR vs Saints, last-second TD.", a:"Stefon Diggs" },
  { q:"Who won unanimous MVP in 2019?", hint:"Ravens QB.", a:"Lamar Jackson" },
  { q:"Who holds the record with 23 receiving TDs?", hint:"2007 Patriots.", a:"Randy Moss" },
  { q:"Which QB popularized the Tush Push?", hint:"Eagles QB.", a:"Jalen Hurts" },
  { q:"Who holds the single-game rushing record of 296 yards?", hint:"Vikings RB.", a:"Adrian Peterson" },
  { q:"Who is the all-time passing TD leader?", hint:"Patriots/Bucs legend.", a:"Tom Brady" },
  { q:"Who made the Immaculate Reception?", hint:"Steelers RB/FB.", a:"Franco Harris" },
  { q:"Who won Super Bowl I?", hint:"Coached by Vince Lombardi.", a:"Green Bay Packers" },
  { q:"Who was the Steelers’ 4-time SB coach?", hint:"1970s dynasty.", a:"Chuck Noll" },
  { q:"Who made 'The Catch'?", hint:"49ers WR.", a:"Dwight Clark" },

  { q:"Who guaranteed a Super Bowl III win?", hint:"Jets QB.", a:"Joe Namath" },
  { q:"Which referee was known for huge biceps?", hint:"Iconic NFL official.", a:"Ed Hochuli" },
  { q:"Which replacement ref ruled the 'Fail Mary'?", hint:"Monday night controversy.", a:"Lance Easley" },
  { q:"'You play to win the game' coach?", hint:"Jets HC.", a:"Herm Edwards" },
  { q:"Patriots coach with 6 Super Bowl wins?", hint:"'The Hoodie'.", a:"Bill Belichick" },
  { q:"Who made the Helmet Catch?", hint:"Giants WR.", a:"David Tyree" },
  { q:"Who threw the Helmet Catch?", hint:"Giants QB.", a:"Eli Manning" },
  { q:"Only undefeated team incl. Super Bowl?", hint:"Perfect season.", a:"1972 Dolphins" },
  { q:"Who returned SB XLI opening kickoff for a TD?", hint:"Bears legend.", a:"Devin Hester" },
  { q:"Who is 'The Sheriff'?", hint:"Colts/Broncos QB.", a:"Peyton Manning" },

  { q:"Who led the drive to beat the Bengals in SB XXIII?", hint:"49ers QB #16.", a:"Joe Montana" },
  { q:"Greatest WR ever?", hint:"49ers legend.", a:"Jerry Rice" },
  { q:"1985 Bears coach?", hint:"Chicago icon.", a:"Mike Ditka" },
  { q:"Who caused the Beast Quake?", hint:"Seahawks RB.", a:"Marshawn Lynch" },
  { q:"'Don’t talk about me' CB?", hint:"Seahawks LOB star.", a:"Richard Sherman" },
  { q:"Who threw the Philly Special TD?", hint:"Eagles TE.", a:"Trey Burton" },
  { q:"Who toe-tapped in SB XLIII?", hint:"Steelers WR.", a:"Santonio Holmes" },
  { q:"'Big Ben' QB?", hint:"Steelers QB.", a:"Ben Roethlisberger" },
  { q:"Hail Mary king vs Lions?", hint:"Packers QB.", a:"Aaron Rodgers" },
  { q:"MNFB 90-yard run legend?", hint:"Raiders RB.", a:"Bo Jackson" },

  { q:"NFL all-time rushing leader?", hint:"Cowboys RB #22.", a:"Emmitt Smith" },
  { q:"Lions RB with insane cutbacks?", hint:"Retired early.", a:"Barry Sanders" },
  { q:"1950s Browns RB GOAT?", hint:"#32.", a:"Jim Brown" },
  { q:"'Get your popcorn ready' WR?", hint:"Star WR.", a:"Terrell Owens" },
  { q:"1998 Vikings rookie phenom?", hint:"Deep threat.", a:"Randy Moss" },
  { q:"'Greatest Show on Turf' RB?", hint:"Dual-threat.", a:"Marshall Faulk" },
  { q:"QB of the Greatest Show on Turf?", hint:"Rams MVP.", a:"Kurt Warner" },
  { q:"Stopped 1 yard short in SB XXXIV?", hint:"Titans WR.", a:"Kevin Dyson" },
  { q:"Goal-line INT SB XLIX?", hint:"Patriots CB.", a:"Malcolm Butler" },
  { q:"SB LIV comeback QB?", hint:"Chiefs #15.", a:"Patrick Mahomes" },

  { q:"Chiefs star TE?", hint:"Future HOF.", a:"Travis Kelce" },
  { q:"Chiefs dynasty coach?", hint:"Big Red.", a:"Andy Reid" },
  { q:"Lost 4 straight SBs?", hint:"Early 90s AFC team.", a:"Buffalo Bills" },
  { q:"SB XXXVI game-winning FG kicker?", hint:"Patriots clutch kicker.", a:"Adam Vinatieri" },
  { q:"100-yard NFC Champ pick-six?", hint:"Bucs legend.", a:"Ronde Barber" },
  { q:"Steelers safety #43?", hint:"Hair icon.", a:"Troy Polamalu" },
  { q:"Shutdown CB 'Island'?", hint:"Jets CB.", a:"Darrelle Revis" },
  { q:"49ers WCO creator?", hint:"Offensive genius.", a:"Bill Walsh" },
  { q:"Cowboys suit-and-hat coach?", hint:"Legendary sideline figure.", a:"Tom Landry" },
  { q:"'They are who we thought they were'?", hint:"Cards coach.", a:"Dennis Green" },

  { q:"'Eat this W' speech?", hint:"QB meme.", a:"Jameis Winston" },
  { q:"'Just win, baby' owner?", hint:"Raiders legend.", a:"Al Davis" },
  { q:"Super Bowl trophy name?", hint:"Named after Packers coach.", a:"Vince Lombardi Trophy" },
  { q:"Cheesehead fans?", hint:"NFC North team.", a:"Green Bay Packers" },
  { q:"Arrowhead Stadium team?", hint:"Loudest stadium.", a:"Kansas City Chiefs" },
  { q:"Lambeau Field team?", hint:"Frozen Tundra.", a:"Green Bay Packers" },
  { q:"'12th Man' fanbase?", hint:"NFC West.", a:"Seattle Seahawks" },
  { q:"'America’s Team'?", hint:"NFC East.", a:"Dallas Cowboys" },
  { q:"Drafted Peyton & Luck?", hint:"Horseshoe logo.", a:"Indianapolis Colts" },
  { q:"Moved from St. Louis to LA in 2016?", hint:"Blue/yellow team.", a:"Los Angeles Rams" },

  { q:"Moved from SD to LA?", hint:"Bolt logo.", a:"Los Angeles Chargers" },
  { q:"199th pick with 7 SBs?", hint:"GOAT.", a:"Tom Brady" },
  { q:"Bengals #1 pick in 2020?", hint:"LSU star.", a:"Joe Burrow" },
  { q:"Packers drafted as Rodgers’ successor?", hint:"#10 QB.", a:"Jordan Love" },
  { q:"Cards QB drafted #1 in 2019?", hint:"Dual-threat.", a:"Kyler Murray" },
  { q:"'Matty Ice'?", hint:"Falcons QB.", a:"Matt Ryan" },
  { q:"OT TD scorer in SB LI?", hint:"Patriots RB #28.", a:"James White" },
  { q:"Julio’s sideline catch SB LI?", hint:"Falcons WR.", a:"Julio Jones" },
  { q:"Edelman juggling catch SB LI?", hint:"Patriots WR.", a:"Julian Edelman" },
  { q:"Immaculate Reception intended target?", hint:"Steelers back.", a:"Frenchy Fuqua" },

  { q:"Ravens LB #52?", hint:"SB XLVII.", a:"Ray Lewis" },
  { q:"NFL career sack leader?", hint:"Bills/Redskins DE.", a:"Bruce Smith" },
  { q:"Giants LB #56 changed defense?", hint:"Pass-rush icon.", a:"Lawrence Taylor" },
  { q:"'Weapon X' safety?", hint:"Eagles #20.", a:"Brian Dawkins" },
  { q:"Cowboys WR #88 in 90s?", hint:"Triplets WR.", a:"Michael Irvin" },
  { q:"Broncos QB lost 3 SBs, won 2?", hint:"#7.", a:"John Elway" },
  { q:"Patriots TE #87?", hint:"Freak athlete.", a:"Rob Gronkowski" },
  { q:"Saints QB with passing yards record?", hint:"#9.", a:"Drew Brees" },
  { q:"Jaguars QB mustache meme?", hint:"Cult hero.", a:"Gardner Minshew" },
  { q:"Bills QB of K-Gun offense?", hint:"90s AFC power.", a:"Jim Kelly" },

  { q:"Steel Curtain team?", hint:"70s defense.", a:"Pittsburgh Steelers" },
  { q:"Team known for 'Dawg Pound' fans?", hint:"AFC North.", a:"Cleveland Browns" },
  { q:"NFC North team named after a big cat?", hint:"Thanksgiving games.", a:"Detroit Lions" },
  { q:"NFC North team with horn logo?", hint:"Purple.", a:"Minnesota Vikings" },
  { q:"AFC West team known for The Black Hole?", hint:"Silver & black.", a:"Las Vegas Raiders" },
  { q:"NFC West bird team?", hint:"Plays in Arizona.", a:"Arizona Cardinals" },
  { q:"'Who Dat' fanbase?", hint:"Superdome.", a:"New Orleans Saints" },
  { q:"Stadium nicknamed 'The Jungle'?", hint:"AFC North.", a:"Cincinnati Bengals" },
  { q:"Team that lost on Music City Miracle?", hint:"1999 playoffs.", a:"Buffalo Bills" },
  { q:"Which QB was at center of Deflategate?", hint:"Patriots QB.", a:"Tom Brady" }
];
